HELM-293: support string properties in performance datasource
OpenNMS/opennms-helm pull request #319
Opened 2021-12-14 12:55 UTC by swachter

Issue: https://issues.opennms.org/browse/HELM-293

This PR adds support for querying string properties to the performance datasource.

@Bonrob2 I also added some documentation; please review.

Open question: I added some information to `query.options.html` but did not find where this would show up when using the performance datasource. Is the help functiionality broken?

2021-12-14 17:55 UTC, Bonrob2 requested changes
Looks good, Stefan. Minor changes.

2021-12-14 17:55 UTC, Bonrob2 commented on docs/modules/datasources/pages/performance_datasource.adoc
> +Used to read the last value of string valued properties that OpenNMS collects and stores. The query is used to identify which string property is queried. A panel can contain multiple string property
```suggestion
Used to read the last value of string-valued properties that OpenNMS collects and stores.
The query identifies which string property is queried. 
A panel can contain multiple string property queries. 
The result can be visualized in a table. 
Use Grafana's transforms like "Filter by name", "Organize Fields", or "Merge" to adjust the visualized table as needed.
```
Each sentence needs to be on a separate line.

2021-12-14 18:58 UTC, RangerRick approved these changes
this looks pretty good to me 👍

2021-12-14 19:49 UTC, mmahacek commented on docs/modules/datasources/pages/performance_datasource.adoc
> +|===
```suggestion
|===
| Name
| Description

| Node
| Node ID of the node to query.
Can also be a variable with a `nodeFilter()` query.

| Resource
| Resource ID containing the requested attribute.
Can also be a variable with a `nodeResources()` query.

| String Property
| Name of the attribute to query.
|===
```

2021-12-14 20:11 UTC, RangerRick approved these changes

2021-12-14 20:12 UTC, Bonrob2 submitted a review, later dismissed
LGTM!

2021-12-14 20:19 UTC, mmahacek requested changes
Modified Signature error with deb on Ubuntu with Grafana 8.3.3

2021-12-14 20:35 UTC, mmahacek commented
And the ZIP from the latest build running on 8.3.3 in Docker has an issue where UI elements aren't displayed. 
![image](https://user-images.githubusercontent.com/26419758/146075425-675e146d-cec0-4318-a7d2-36dcb3af6271.png)

2021-12-14 20:53 UTC, RangerRick requested changes
please rebase this to `release-7.x`

2021-12-15 17:17 UTC, swachter commented
rebased on 7.x; please review again

2021-12-15 17:21 UTC, mmahacek approved these changes
This works for me on Grafana 8.3.3 on both Ubuntu and Docker.

2021-12-15 18:09 UTC, RangerRick submitted a review, later dismissed

2021-12-15 18:13 UTC, swachter commented
I am sorry, I have to make another small change. Simply throwing an error in case that string property queries are mixed with other kinds of queries does not yield to an error message in the view. The fix is to return a proper response with an error message.

2021-12-15 19:49 UTC, RangerRick approved these changes
ah yeah, good catch

2021-12-16 15:49 UTC, merged