HELM-326: Add documentation for location() template_variable
OpenNMS/opennms-helm pull request #415
Opened 2022-05-11 17:48 UTC by aramosvizcarra

Added documentation and examples for new location() template variable

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-326
* Continuous Integration: [CircleCI](https://circleci.com/gh/OpenNMS/opennms-helm)

2022-05-11 18:51 UTC, Bonrob2 requested changes
A few minor changes.

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/entity_datasource.adoc
> +The `nodeFilter()` query will return a list of nodes which match the given filter expression.
```suggestion
The `nodeFilter()` query returns a list of nodes which match the given filter expression.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/entity_datasource.adoc
> +Example: +
```suggestion
Example: 
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
> +Use this variable with exporterNodesWithFlows to reduce the number of nodes displayed by location.
```suggestion
Use this variable with `exporterNodesWithFlows` to reduce the number of nodes displayed by location.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
> +Examples: +
```suggestion
Examples:
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
>  The `exporterNodesWithFlows()` query will return a list of nodes which have exported flow data to OpenNMS.
```suggestion
The `exporterNodesWithFlows()` query returns a list of nodes which have exported flow data to OpenNMS.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
> +The filter expression must be an existing node attribute and their corresponding value and the value can be constant or a template_variable.
```suggestion
The filter expression must be an existing node attribute and its corresponding value.
The value can be a constant or a template_variable.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
> +Example: +
```suggestion
Example:
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
>  The `interfacesOnExporterNodeWithFlows()` query will return a list of interface indexes which are associated with one or more flows on the given node.
```suggestion
The `interfacesOnExporterNodeWithFlows()` query returns a list of interface indexes which are associated with one or more flows on the given node.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/performance_datasource.adoc
> +Examples: +
```suggestion
Examples:
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/performance_datasource.adoc
>  The `nodeFilter()` query will return a list of nodes which match the given filter expression.
```suggestion
The `nodeFilter()` query returns a list of nodes which match the given filter expression.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/entity_datasource.adoc
> +Use this variable with nodeFilter to reduce the number of nodes displayed by location.
```suggestion
Use this variable with `nodeFilter` to reduce the number of nodes displayed by location.
```

2022-05-11 18:51 UTC, Bonrob2 commented on docs/modules/datasources/pages/flow_datasource.adoc
> +Use this variable with exporterNodesWithFlows to reduce the number of nodes displayed by location.
```suggestion
Use this variable with `exporterNodesWithFlows` to reduce the number of nodes displayed by location.
```

2022-05-11 18:52 UTC, mmahacek reviewed
It would be helpful to include example of using a location filter along with a service or category filter. For the performance/flow data sources, I'm thinking it might be better to have the `location()` filter after the filters already in the docs, to highlight `nodeFitler` and `exporterNodesWithFlows` as the primary filters for those.

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/performance_datasource.adoc
> +
```suggestion
Examples: 

* nodeFilter(location='Default')
* nodeFilter(location='$location')

```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +```
```suggestion
Example:

* exporterNodesWithFlows(location='Default')
```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +```
```suggestion
Examples:

* exporterNodesWithFlows(location='Default')
* exporterNodesWithFlows(location='$location')
```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +```
```suggestion
Example:

```
* nodeFilter(location='Default')
```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +```
```suggestion
Examples:

* nodeFilter(location='Default')
* nodeFilter(location='$location')
```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +Use this variable with nodeFilter to reduce the number of nodes displayed by location.
```suggestion
Use this variable with `nodeFilter()` to reduce the number of nodes displayed by location.
```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +Use this variable with exporterNodesWithFlows to reduce the number of nodes displayed by location.
```suggestion
Use this variable with `exporterNodesWithFlows()` to reduce the number of nodes displayed by location.
```

2022-05-11 18:52 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +The filter expression must be an existing node attribute and their corresponding value and the value can be constant or a template_variable.
The wording on this seems a little confusing (too many "and/or") for a new user.  Not sure a suggestion yet - need to re-read this section.

2022-05-16 20:39 UTC, mmahacek reviewed
Can you include at least one example of including location and other filters?  I'm assuming it is something like `nodeFilter(location='Default' & isSNMP)` but would be good to show an example for users that are including multiple criteria in the filter syntax.

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +Use this variable with `nodeFilter()` to reduce the number of nodes displayed by location.
```suggestion
Use this inside `nodeFilter()` to filter the number of nodes displayed by location.
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +The value can be a constant or a template_variable.
Grafana just calls them "variables" now instead of template variables.
```suggestion
The value can be a constant or a variable.
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +Use this variable with `exporterNodesWithFlows()` to reduce the number of nodes displayed by location.
```suggestion
Use this inside `exporterNodesWithFlows()` to filter the number of nodes displayed by location.
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +The value can be a constant or a template_variable.
```suggestion
The value can be a constant or a variable.
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +```
```suggestion
.Example variable expression
exporterNodesWithFlows(location='Default')
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/flow_datasource.adoc
> +```
```suggestion
.Example variable expression
* exporterNodesWithFlows(location='Default')
* exporterNodesWithFlows(location='$location')
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/entity_datasource.adoc
> +```
The triple backtick notation for code blocks isn't used by the documentation system.  This should be a list instead.
```suggestion
.Example variable expression
* nodeFilter(location='Default')
* nodeFilter(location='$location')
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/performance_datasource.adoc
> +```
```suggestion
.Example variable expression
* nodeFilter(location='Default')
* nodeFilter(location='$location')
```

2022-05-16 20:39 UTC, mmahacek commented on docs/modules/datasources/pages/performance_datasource.adoc
>  Use this variable with nodeFilter to reduce the number of nodes displayed by location.
```suggestion
Use this inside `nodeFilter()` to filter the number of nodes displayed by location.
```

2022-05-25 19:06 UTC, aramosvizcarra commented
> Can you include at least one example of including location and other filters? I'm assuming it is something like `nodeFilter(location='Default' & isSNMP)` but would be good to show an example for users that are including multiple criteria in the filter syntax.

I added a few more. Note that only Performance DS supports the node filter criteria like catinc or isSNMP since is based on the rest API used. Entities and Flows do the filtering on the front-end and can only filter based on the node info retrived by each.

2022-05-25 20:10 UTC, mmahacek approved these changes
Thank you.  These extra samples will help.

2022-05-25 20:11 UTC, mmahacek commented
@Bonrob2 This is ready for another review pass

2022-05-25 20:30 UTC, Bonrob2 approved these changes
LGTM!

2022-05-26 12:02 UTC, merged