HELM-359: migrating helm unit tests to react
OpenNMS/opennms-helm pull request #565
Opened 2022-11-17 23:04 UTC by aramosvizcarra

feat: added initial test for flow datasources and along included a few fixes for the react flow datasource

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-359
* Continuous Integration: [CircleCI](https://circleci.com/gh/OpenNMS/opennms-helm)

2022-11-18 14:54 UTC, scthompsonopen requested changes

2022-11-18 14:54 UTC, scthompsonopen commented on src/datasources/flow-ds-react/helpers.ts
> +                const datapoints = timestampsInRange
Can we break this out into its own function? We've hit more levels of indentation here than I'm comfortable with.

2022-11-18 14:54 UTC, scthompsonopen commented on src/datasources/flow-ds-react/helpers.ts
> +                const datapoints = timestampsInRange
Also, can we use more descriptive variable names (sum of what, what column index, prv/cur context), move the inline comments into a jsdoc comment explaining what the whole block is doing. I want to move away from the very long functions in the existing Helm code.

2022-12-01 18:09 UTC, aramosvizcarra commented
closing as I ended up separating this jira into test per datasource and any other test affected by this migration.

2022-12-01 18:09 UTC, closed without merging